fix: fixing this error
credits: 
https://github.com/developmentseed/label-maker/commit/94f1863945c47e1b69fe0d6d575caa0b42aa8d63 

ValueError: SSD Inception V2 feature extractor always usesscope returned 
by `conv_hyperparams_fn` for both the base feature extractor and the 
additional layers added since there is no arg_scope defined for the base 
feature extractor.